### PR TITLE
OCPBUGS-42240: Refine security context

### PR DESCRIPTION
**Pull request by aleskandro**
This PR makes the security contexts of the workloads managed by the MTO and the MTO deployment explicit so that DAST is happy.

### CODE REVIEW

**Comment by lwan-wanglin** [comment]
retest

**Comment by lwan-wanglin** [comment]
the test pass with image quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator/multiarch-tuning-operator-bundle:on-pr-a8ac9d23493a9576ab66149e67d4c956fb370336

```
trivy k8s --kubeconfig=/home/rapidast/.kube/config -n openshift-multiarch-tuning-operator all --severity=HIGH,CRITICAL --scanners=misconfig --report all --format json -o /tmp/k8s_result.json && python3 convert_trivy_k8s_to_sarif.py -f /tmp/k8s_result.json
74.86 KiB / 74.86 KiB [-----------------------------------------------------------------------------------------------] 100.00% ? p/s 0s
17 / 17 [----------------------------------------------------------------------------------------------------------------] 100.00% 2 p/s
{
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Trivy-k8s",
          "version": "0.49.1",
          "rules": []
        }
      },
      "results": []
    }
  ]
}
INFO:The generic process finished correctly, and exited with code 0
```

**Comment by aleskandro** [comment]
e2e-gcp-multi-operator  actually passed, a post step failed

**Pull request merged**
