### PR TITLE
Fix failing Konflux tests

### PR DESCRIPTION
**Pull request by AnnaZivkovic**
Konflux pipeline runs are failing with 
```
[Violation] tasks.required_tasks_found
  ImageRef: quay.io/redhat-user-workloads/multiarch-tuning-ope-tenant/multiarch-tuning-operator/multiarch-tuning-operator-bundle@sha256:ec6f55f3eaac12394e654fd6e8c158e5c626aef1b49009f50931789973aebfff
  Reason: Required task "rpms-signature-scan" is missing
  Title: All required tasks were included in the pipeline
  Description: Ensure that the set of required tasks are included in the PipelineRun attestation. To exclude this rule add
  "tasks.required_tasks_found:rpms-signature-scan" to the `exclude` section of the policy configuration.
  Solution: Make sure all required tasks are in the build pipeline. The required task list is contained as
  xref:ec-cli:ROOT:configuration.adoc#_data_sources[data] under the key 'required-tasks'.|
  ```
  Added rpms-signature-scan to fix issue 
  Using https://github.com/enterprise-contract/golden-container/blob/d3f9845fa73a46b77275db3365b57dbfb974f8c8/.tekton/build-pipeline.yaml#L322-L343 as a template 
  Docs: https://github.com/konflux-ci/build-definitions/tree/main/task/rpms-signature-scan/0.2

### CODE REVIEW

**Comment by aleskandro** [comment]
Hi, this looks good to me. Can you verify the failures in the EC before "/approve"?

/lgtm

**Comment by AnnaZivkovic** [comment]
Ran again to get the logs. The errors are all part of enterprise contract

**Review by aleskandro — APPROVED** [review]

**Pull request merged**
