### PR TITLE
MULTIARCH-4306:  avoid the possibility of deleting the operand togeth…

### PR DESCRIPTION
**Pull request by AnnaZivkovic**
…er with the uninstallation of the operator.

### CODE REVIEW

**Comment by Prashanth684** [comment]
looks good - but is there a way to test it by creating a catalog and adding the operator to it?

**Comment by aleskandro** [comment]
> level=info msg="[linters_context/goanalysis] analyzers took 3h17m2.114385817s with top 10 stages: buildir: 46m54.930301245s,

We really need to understand what's going on with the lint job (failing in a lot of PRs randomly)

/test lint

Maybe @lwan-wanglin can help with testing this behavior manually? I'd avoid an automated test for this as it would require GUI-related testing tools.

**Comment by lwan-wanglin** [comment]
> Maybe @lwan-wanglin can help with testing this behavior manually? I'd avoid an automated test for this as it would require GUI-related testing tools.

sure, I will test it manually.

**Comment by aleskandro** [comment]
/override "Red Hat Konflux / multiarch-tuning-operator-enterprise-contract"

**Comment by aleskandro** [comment]
/override "Red Hat Konflux / multiarch-tuning-operator-fs25p / multiarch-tuning-operator-enterprise-contract"

**Pull request merged**
